### ISSUE TITLE
Books which are not in A4 format get ruined in download

### ISSUE THREAD

**Issue by felixtech-msp** [garzj/d4sd#5]
When trying to download books which are not in DIN A4 format, the pages get squished in the height of A4 and the width is then larger than A4 and the content just gets cut off on the right side.

**Comment by garzj** [comment]
Did you try the `--format` option? It can be either of the following:
letter, legal, tabloid, ledger, a0, a1, a2, a3, a4, a5, a6

[Here](https://pptr.dev/api/puppeteer.paperformat) you can find the exact dimensions. They should cover most cases.

**Comment by felixtech-msp** [comment]
From further testing I have seen that the issue is not even the format. Some books which have those scaling problems are indeed A4 but the pages are not fitted into the A4 output page and instead too wide and too high making them effectively totally broken (see screenshot). If the image size would be reduced to fit into the page it would work.
Account with test books see e-mail.

![grafik](https://github.com/garzj/d4sd/assets/89098885/2deaae57-1593-40b9-9e27-389c66b6c24e)

**Comment by garzj** [comment]
Thanks for the insight. I realized that the width and height for these pages weren't set on the SVGs themselves, but rather on the digi4school wrapper, so the browser wan't able to determine what to capture, regardless of the format.
Copying and setting these values helped.
